### ISSUE TITLE
Don't assume first name is the substring before the first space

### ISSUE THREAD

**Issue by ben-z** [WATonomous/user-config-lookup#10]
There's an assumption here that the first name is the substring before the first space. This is not always the case. We should just use the information available (full name) to ensure correctness.

https://github.com/WATonomous/user-config-lookup/blob/3c95c2ad3d7ec85522bbb06b83206eff633d01c4/app/email.py#L26

**Comment by Jimmyj30** [comment]
Sounds good, just wondering when this would be the case? I guess if someone decided to put a title before their name or something xd

**Comment by ben-z** [comment]
Oh e.g. my legal first name has a space in it :P
