### ISSUE TITLE
Unexpected EOF received

### ISSUE THREAD

**Issue by ben-z** [WATonomous/user-config-lookup#9]
After sending a successful email, there's always this error in the log:

```
Future exception was never retrieved
future: <Future finished exception=SMTPServerDisconnected('Unexpected EOF received')>
aiosmtplib.errors.SMTPServerDisconnected: Unexpected EOF received
```

<img width="1264" alt="image" src="https://github.com/WATonomous/user-config-lookup/assets/5977478/e3ff9e56-d310-4a58-9f3d-b369bb199f20">

**Comment by ben-z** [comment]
I used this to see logs:
```bash
sudo kubectl -n user-config-lookup logs deployment.apps/user-config-lookup -f
```

**Comment by Jimmyj30** [comment]
Possibly relevant thread?

https://github.com/cole/aiosmtplib/issues/112

Seems to not impact the "functionality" of the app but maybe I can poke around with different versions of the email library
